ARG grafana_version=11.6.2
FROM grafana/grafana:${grafana_version}

# Copy provisioning files from the correct path
COPY release/config/grafana_volumes/provisioning /etc/grafana/provisioning

# Inject warp10.conf
COPY release/config/warp10.conf /opt/warp10/etc/warp10.conf
